/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.emp.gl.gui;

import java.util.ArrayList;
import org.emp.gl.authenticity.implementations.SignatureRSA;
import org.emp.gl.confidentiality.implementations.RSA;
import org.emp.gl.confidentiality.implementations.Shift;
import org.emp.gl.core.lookup.Lookup;
import org.emp.gl.filtre.implementations.LowerCase;
import org.emp.gl.filtre.implementations.NoSpace;
import org.emp.gl.filtre.implementations.NoSpecialCharacter;
import org.emp.gl.filtre.implementations.UpperCase;
import org.emp.gl.integrity.implementations.Length;
import org.emp.gl.integrity.implementations.MD5;
import org.emp.gl.integrity.implementations.SHA;
import org.emp.gl.messages.BaseMessageAdapter;
import org.emp.gl.messages.IMessage;
import org.emp.gl.sender.service.MessagingService;

/**
 *
 * @author younes
 */
public class MySenderGui extends javax.swing.JFrame {
    
    private final String senderId;
    private boolean[] internal_state={false,false,false,false,false,false,false,false,false,false};
    IMessage message;
    /**
     * Creates new form MySenderGui
     */
    public MySenderGui(String senderId) {
        this.senderId=senderId;
        initComponents();
        message = new BaseMessageAdapter();
        message.setMessage("");
        senderInput.setText(senderId);
        objectInput.setText(" object ");
        receiverInput.setText("ID-1");
    }
    private void applyDecorations(){
        message.setMessage(messageInput.getText());
        
           if(internal_state[0]){
             message=new UpperCase(message);
           }

           if(internal_state[1]){
             message=new LowerCase(message);
           }

           if(internal_state[2]){
              message=new NoSpace(message);
           }

           if(internal_state[3]){
              message=new NoSpecialCharacter(message);
           }

           if(internal_state[4]){
               message=new MD5(message);
           }

           if(internal_state[5]){
                message=new RSA(message);
           }

           if(internal_state[6]){
                message=new Shift(message,5);
           }

           if(internal_state[7]){
               message=new SHA(message);
           }

           if(internal_state[8]){
                message=new Length(message);
           }


           if(internal_state[9]){
                message=new SignatureRSA(message);
           }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageInput = new javax.swing.JTextArea();
        receiverInput = new javax.swing.JTextField();
        senderInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        objectInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sendBtn = new javax.swing.JButton();
        upperCase = new javax.swing.JCheckBox();
        lowerCase = new javax.swing.JCheckBox();
        noSpace = new javax.swing.JCheckBox();
        noSpecialCharacters = new javax.swing.JCheckBox();
        md5 = new javax.swing.JCheckBox();
        sha = new javax.swing.JCheckBox();
        length = new javax.swing.JCheckBox();
        signatureRSA = new javax.swing.JCheckBox();
        shift = new javax.swing.JCheckBox();
        rsa = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(137, 187, 237));

        messageInput.setColumns(20);
        messageInput.setRows(5);
        jScrollPane1.setViewportView(messageInput);

        receiverInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        senderInput.setEditable(false);
        senderInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Sender");

        jLabel3.setText("Message");

        jLabel4.setText("Receiver");

        objectInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText("Object");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(objectInput))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(senderInput))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(receiverInput, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senderInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiverInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(objectInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Decor");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        sendBtn.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        sendBtn.setForeground(new java.awt.Color(25, 182, 19));
        sendBtn.setText("Send");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        upperCase.setText("UpperCase");
        upperCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upperCaseActionPerformed(evt);
            }
        });

        lowerCase.setText("LowerCase");
        lowerCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerCaseActionPerformed(evt);
            }
        });

        noSpace.setText("NoSpace");
        noSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSpaceActionPerformed(evt);
            }
        });

        noSpecialCharacters.setText("NoSpecialChars");
        noSpecialCharacters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noSpecialCharactersActionPerformed(evt);
            }
        });

        md5.setText("MD5");
        md5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md5ActionPerformed(evt);
            }
        });

        sha.setText("SHA");
        sha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shaActionPerformed(evt);
            }
        });

        length.setText("Length");
        length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthActionPerformed(evt);
            }
        });

        signatureRSA.setText("SignatureRSA");
        signatureRSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signatureRSAActionPerformed(evt);
            }
        });

        shift.setText("Shift");
        shift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftActionPerformed(evt);
            }
        });

        rsa.setText("RSA");
        rsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sendBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(length)
                            .addComponent(rsa)
                            .addComponent(noSpecialCharacters)
                            .addComponent(lowerCase)
                            .addComponent(upperCase)
                            .addComponent(noSpace)
                            .addComponent(md5)
                            .addComponent(sha)
                            .addComponent(shift)
                            .addComponent(signatureRSA))
                        .addContainerGap(77, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(upperCase)
                        .addGap(18, 18, 18)
                        .addComponent(lowerCase)
                        .addGap(18, 18, 18)
                        .addComponent(noSpace)
                        .addGap(18, 18, 18)
                        .addComponent(noSpecialCharacters)
                        .addGap(18, 18, 18)
                        .addComponent(md5)
                        .addGap(18, 18, 18)
                        .addComponent(sha)
                        .addGap(18, 18, 18)
                        .addComponent(length)
                        .addGap(18, 18, 18)
                        .addComponent(rsa)
                        .addGap(18, 18, 18)
                        .addComponent(shift)
                        .addGap(18, 18, 18)
                        .addComponent(signatureRSA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        message.setTitle(objectInput.getText());
        message.setSender(senderInput.getText());
        applyDecorations();
        MessagingService ms = Lookup.getInstance().getService(MessagingService.class);
        ms.sendMessage(receiverInput.getText(), message.toString());
        message.setMessage("");
        messageInput.setText("");
    }//GEN-LAST:event_sendBtnActionPerformed

    private void upperCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upperCaseActionPerformed
        // TODO add your handling code here:
        internal_state[0]=!internal_state[0];
    }//GEN-LAST:event_upperCaseActionPerformed

    private void lowerCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerCaseActionPerformed
        // TODO add your handling code here:
         internal_state[1]=!internal_state[1];
    }//GEN-LAST:event_lowerCaseActionPerformed

    private void noSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noSpaceActionPerformed
        // TODO add your handling code here:
         internal_state[2]=!internal_state[2];
    }//GEN-LAST:event_noSpaceActionPerformed

    private void noSpecialCharactersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noSpecialCharactersActionPerformed
        // TODO add your handling code here:
         internal_state[3]=!internal_state[3];
    }//GEN-LAST:event_noSpecialCharactersActionPerformed

    private void md5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md5ActionPerformed
        // TODO add your handling code here:
         internal_state[4]=!internal_state[4];
    }//GEN-LAST:event_md5ActionPerformed

    private void shaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shaActionPerformed
        // TODO add your handling code here:
         internal_state[7]=!internal_state[7];
    }//GEN-LAST:event_shaActionPerformed

    private void lengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthActionPerformed
        // TODO add your handling code here:
         internal_state[8]=!internal_state[8];
    }//GEN-LAST:event_lengthActionPerformed

    private void rsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsaActionPerformed
        // TODO add your handling code here:
         internal_state[5]=!internal_state[5];
    }//GEN-LAST:event_rsaActionPerformed

    private void shiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftActionPerformed
        // TODO add your handling code here:
         internal_state[6]=!internal_state[6];
    }//GEN-LAST:event_shiftActionPerformed

    private void signatureRSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signatureRSAActionPerformed
        // TODO add your handling code here:
         internal_state[9]=!internal_state[9];
    }//GEN-LAST:event_signatureRSAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox length;
    private javax.swing.JCheckBox lowerCase;
    private javax.swing.JCheckBox md5;
    private javax.swing.JTextArea messageInput;
    private javax.swing.JCheckBox noSpace;
    private javax.swing.JCheckBox noSpecialCharacters;
    private javax.swing.JTextField objectInput;
    private javax.swing.JTextField receiverInput;
    private javax.swing.JCheckBox rsa;
    private javax.swing.JButton sendBtn;
    private javax.swing.JTextField senderInput;
    private javax.swing.JCheckBox sha;
    private javax.swing.JCheckBox shift;
    private javax.swing.JCheckBox signatureRSA;
    private javax.swing.JCheckBox upperCase;
    // End of variables declaration//GEN-END:variables
}
